version: '3.8'
services:
  movies:
    image: haryyb43/movies1:latest
    ports:
      - "95:80"
    deploy:
      replicas: 3
      train:
    image: haryyb43/train1:latest
    ports:
      - "96:80"
    deploy:
      replicas : 3
  dth:
    image: haryyb43/dth1:latest
    ports:
      - "97:80"
    deploy :
      replicas : 3
  recharge:
    image: haryyb43/recharge1:latest
    ports:
      - "98:80"
    deploy :
      replicas : 3

